registries:
  codeartifact-feed:
    type: npm-registry
    url: https://registry-prod-904690835784.d.codeartifact.eu-west-2.amazonaws.com/npm/registry-prod-repo
    aws-region: eu-west-2
    domain: registry-prod
    domain-owner: '904690835784'
    account-id: ${{ secrets.DEPENDABOT_CODEARTIFACT_ACCOUNT }}
    role-name: ${{ secrets.DEPENDABOT_CODEARTIFACT_ROLE_NAME }}

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    registries:
      - codeartifact-feed
