sonar.organization=govuk-once
sonar.projectKey=govuk-once_gds-unified-notification-service

sonar.sources=src,infrastructure/cdk
sonar.typescript.tsconfigPaths=tsconfig.json
sonar.exclusions=dist/**,coverage/**,**/**.test.unit.ts,**/**.test.util.ts,**/**.mocks.ts,**/**.vitest.ts,infrastructure/cdk/cdk.out, infrastructure/cdk/cdk.context.json
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
