sonar.organization=govuk-once
sonar.projectKey=govuk-once_gds-unified-notification-service

sonar.sources=src,terraform
sonar.typescript.tsconfigPaths=tsconfig.json
sonar.exclusions=dist/**,coverage/**,**/**.test.unit.ts
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.terraform.provider.aws.version=6.25.0
