/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Unified Notification Service v0.1 - Flex integration
 * Work in progress
 * OpenAPI spec version: v0.1
 */
import * as zod from 'zod';

/**
 * @summary Gets users notifications
 */
export const GetNotificationsQueryParams = zod.object({
  "externalUserID": zod.string()
})

export const GetNotificationsResponseItem = zod.object({
  "NotificationID": zod.string().describe('ID of the notification to be used for idempotency & analytics'),
  "Status": zod.enum(['RECEIVED', 'READ', 'MARKED_AS_UNREAD']),
  "NotificationTitle": zod.string().describe('Title of the notification to be displayed on mobile device'),
  "NotificationBody": zod.string().describe('Contents of the notification to be displayed on push notification'),
  "DispatchedDateTime": zod.iso.datetime({}),
  "MessageTitle": zod.string().optional().describe('(Optional) Title of the message displayed in the GovUK app\'s notification centre, falls back on notification title'),
  "MessageBody": zod.string().optional().describe('(Optional) Contents of the message displayed in the GovUK app\'s notification centre, falls back on notification body')
})
export const GetNotificationsResponse = zod.array(GetNotificationsResponseItem).min(1).max(50)


/**
 * @summary Gets notification by ID
 */
export const GetNotificationByIDParams = zod.object({
  "notificationID": zod.string()
})

export const GetNotificationByIDQueryParams = zod.object({
  "externalUserID": zod.string()
})

export const GetNotificationByIDResponse = zod.object({
  "NotificationID": zod.string().describe('ID of the notification to be used for idempotency & analytics'),
  "Status": zod.enum(['RECEIVED', 'READ', 'MARKED_AS_UNREAD']),
  "NotificationTitle": zod.string().describe('Title of the notification to be displayed on mobile device'),
  "NotificationBody": zod.string().describe('Contents of the notification to be displayed on push notification'),
  "DispatchedDateTime": zod.iso.datetime({}),
  "MessageTitle": zod.string().optional().describe('(Optional) Title of the message displayed in the GovUK app\'s notification centre, falls back on notification title'),
  "MessageBody": zod.string().optional().describe('(Optional) Contents of the message displayed in the GovUK app\'s notification centre, falls back on notification body')
})


/**
 * @summary Deletes notification by ID
 */
export const DeleteNotificationByIDParams = zod.object({
  "notificationID": zod.string()
})

export const DeleteNotificationByIDQueryParams = zod.object({
  "externalUserID": zod.string()
})


/**
 * @summary Update status of notification
 */
export const PatchNotificationByIDParams = zod.object({
  "notificationID": zod.string()
})

export const PatchNotificationByIDQueryParams = zod.object({
  "externalUserID": zod.string()
})

export const PatchNotificationByIDBody = zod.object({
  "Status": zod.enum(['RECEIVED', 'READ', 'MARKED_AS_UNREAD']).optional()
})
