/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Unified Notification Service v0.1 - PSO
 * Work in progress
 * OpenAPI spec version: v0.1
 */
import * as zod from 'zod';

/**
 * @summary Gets service status
 */
export const GetStatusResponse = zod.object({
  "status": zod.boolean()
})


/**
 * @summary Sends notifications
 */
export const PostMessageBodyItem = zod.object({
  "DepartmentID": zod.string().describe('ID of department sending notification'),
  "NotificationID": zod.uuid().optional().describe('ID of the notification to be used for idempotency & analytics, ID will be dynamically generated if one has not been supplied'),
  "UserID": zod.string().describe('ID of the recipient fetched from UDP'),
  "NotificationTitle": zod.string().describe('Title of the notification to be displayed on mobile device'),
  "NotificationBody": zod.string().describe('Contents of the notification to be displayed on push notification'),
  "MessageTitle": zod.string().optional().describe('(Optional) Title of the message displayed in the GovUK app\'s notification centre, falls back on notification title'),
  "MessageBody": zod.string().optional().describe('(Optional) Contents of the message displayed in the GovUK app\'s notification centre, falls back on notification body'),
  "DeeplinkURL": zod.string().optional().describe('Deeplink url to show the notification centre')
})
export const PostMessageBody = zod.array(PostMessageBodyItem).min(1).max(10)


/**
 * @summary Gets status of notification
 */
export const GetNotificationStatusParams = zod.object({
  "notificationID": zod.string()
})

export const GetNotificationStatusResponseItem = zod.object({
  "NotificationID": zod.string(),
  "EventDateTime": zod.string(),
  "Status": zod.enum(['RECEIVED', 'VALIDATING', 'VALIDATED', 'VALIDATION_FAILED', 'PROCESSING', 'PROCESSED', 'PROCESSING_FAILED', 'DISPATCHING', 'DISPATCHED', 'DISPATCHING_FAILED', 'DELIVERED', 'NOTIFICATION_CENTRE_READ', 'NOTIFICATION_CENTRE_MARKED_AS_UNREAD', 'NOTIFICATION_CENTRE_HIDDEN']),
  "Reason": zod.string().optional().describe('Provides addition context to the state')
})
export const GetNotificationStatusResponse = zod.array(GetNotificationStatusResponseItem).min(1).max(10)
