export enum ValidationEnum {
  UNKNOWN = 'UNKNOWN',

  RECEIVED = 'RECEIVED',

  VALIDATING = 'VALIDATING',
  VALIDATED = 'VALIDATED',
  VALIDATED_API_CALL = 'VALIDATED_API_CALL',
  VALIDATION_FAILED = 'VALIDATION_FAILED',

  PROCESSING = 'PROCESSING',
  PROCESSED = 'PROCESSED',
  PROCESSING_FAILED = 'PROCESSING_FAILED',

  DISPATCHING = 'DISPATCHING',
  DISPATCHED = 'DISPATCHED',
  DISPATCHING_FAILED = 'DISPATCHING_FAILED',

  READ = 'READ',
  MARKED_AS_UNREAD = 'MARKED_AS_UNREAD',
  HIDDEN = 'HIDDEN',
}
