version: 0.2

batch:
  build-graph:
    - identifier: pso_scan
      env:
        variables:
          ZAP_TARGET: pso
    - identifier: flex_scan
      env:
        variables:
          ZAP_TARGET: flex

env:
  variables:
    ZAP_IMAGE: 'zaproxy/zap-stable'

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - echo 'Running Scripts'
      - corepack enable
      - aws codeartifact login --tool npm --repository registry-prod-repo --domain registry-prod --domain-owner 904690835784 --region eu-west-2
  pre_build:
    commands:
      - echo "RUNNING ${ZAP_TARGET}" && eval "$(pnpm --silent tsx scripts/runZapProxy.ts --target ${ZAP_TARGET})" && echo "DONE ${ZAP_TARGET}"
      - docker pull $ZAP_IMAGE
      - chmod 644 client.p12
      - chmod -R 777 $(pwd)/infrastructure/cdk/buildspecs/

  build:
    commands:
      - >-
        docker run --network host -v "$(pwd)":/zap/wrk/:rw -e TARGET_SPEC="${TARGET_SPEC}" -e TARGET_URL="${TARGET_URL}" -e ZAP_AUTH_HEADER="x-api-key" -e ZAP_AUTH_HEADER_VALUE="${X_API_KEY}" -t zaproxy/zap-stable zap.sh -cmd -autorun /zap/wrk/infrastructure/cdk/buildspecs/zap.yaml
  post_build:
    commands:
      - cd infrastructure/cdk/buildspecs/
      - DATE=$(date +%Y-%m-%d)
      - TIMESTAMP=$(date +%Y-%m-%dT%H:%M:%S)
      - BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD | tr '/' '_')
      - >-
        for f in *.md; do
          [ -f "$f" ] || continue;
          aws s3 cp "$f" "s3://${UNS_REPORT_BUCKET}/${DATE}/${ZAP_TARGET}-${BRANCH_NAME}-${TIMESTAMP}-${CODEBUILD_BUILD_NUMBER}.md";
        done
