name: Release to env

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: 'Github environment to use'
        type: string
        required: true
      VERSION:
        description: 'Version label'
        type: string
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    timeout-minutes: 60
    steps:
      # Setup
      - name: ⚙️ Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Show OIDC claims (right before assume)
        if: ${{ runner.debug }}
        env:
          AUDIENCE: 'sts.amazonaws.com'
        run: |
          TOKEN_JSON=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$AUDIENCE")
          ID_TOKEN=$(echo "$TOKEN_JSON" | jq -r .value)
          echo "$ID_TOKEN" | awk -F. '{print $2}' | base64 -d 2>/dev/null | jq -r '.sub'

      - name: ⚙️ Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: ⚙️ Configure Codeartifact
        run: aws codeartifact login --tool npm --repository registry-prod-repo --domain registry-prod --domain-owner ${{ secrets.AWS_CODEARTIFACT_ACCOUNT_ID }} --region eu-west-2

      - name: ⚙️ Setup pnpm
        uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.node-version'
          cache: pnpm

      - name: ⚙️ Install Dependencies
        run: pnpm install

      # Build & release
      - name: 🔨 Build bundles
        run: pnpm build

      - name: 🏗️ CDK Deploy
        run: pnpm cdk:deploy
        env:
          region: ${{ vars.AWS_REGION }}
          env: '${{ vars.ENVIRONMENT_SHORTHAND }}'
          code_version: ${{ inputs.VERSION }}
          use_mtls: 'true'
          is_main_environment_in_account: 'true'

      # End to end testing
      - name: 🧪 E2E Testing
        run: VITEST_SILENT=true pnpm test:e2e
        env:
          env: '${{ vars.ENVIRONMENT_SHORTHAND }}'
