name: Deploy environment (Manual)
on:
  workflow_dispatch:
    inputs:
      deploy_to_dev:
        description: 'Deploy to Dev'
        type: boolean
        required: true
      deploy_to_stg:
        description: 'Deploy to Staging'
        type: boolean
        required: true
      deploy_to_prod: # This will be removed after initial deployment pipeline has been setup
        description: 'Deploy to Prod'
        type: boolean
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  releaseDev:
    if: ${{ inputs.deploy_to_dev }}
    name: Deploy to dev
    uses: ./.github/workflows/_deploy.yml
    with:
      ENVIRONMENT: dev
      VERSION: ${{ github.ref_name }}@${{ github.sha }}
    secrets: inherit

  releaseStaging:
    if: ${{ inputs.deploy_to_stg }}
    name: Deploy to staging
    uses: ./.github/workflows/_deploy.yml
    with:
      ENVIRONMENT: staging
      VERSION: ${{ github.ref_name }}@${{ github.sha }}
    secrets: inherit

  releaseProduction:
    if: ${{ inputs.deploy_to_prod }}
    name: Deploy to production
    uses: ./.github/workflows/_deploy.yml
    with:
      ENVIRONMENT: production
      VERSION: ${{ github.ref_name }}@${{ github.sha }}
    secrets: inherit
