name: PR Clean Up pipeline

on:
  # Trigger the workflow on pull request merge or closure
  pull_request:
    types:
      - closed

permissions:
  contents: read
  id-token: write

jobs:
  pr:
    runs-on: ubuntu-latest
    environment:
      name: dev
    timeout-minutes: 60
    steps:
      - name: ⚙️ Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: ⚙️ Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: ⚙️ Configure Codeartifact
        run: aws codeartifact login --tool npm --repository registry-prod-repo --domain registry-prod --domain-owner ${{ secrets.AWS_CODEARTIFACT_ACCOUNT_ID }} --region eu-west-2

      - name: ⚙️ Setup pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.node-version'
          cache: pnpm

      - name: ⚙️ Install Dependencies
        run: pnpm ci

      # Build & destroy
      - name: 🔨 Build bundles
        run: pnpm run build

      - name: 💣 CDK Ephemeral Build Removal
        run: pnpm run cdk destroy uns-${{github.event.number}}-stack --force true && pnpm run cdk:ephemeral:cleanup:ssm
        env:
          pr_number: ${{ github.event.number }}
          region: ${{ vars.AWS_REGION }}
          env: ${{ github.event.number }}
