name: PR pipeline

on:
  # Trigger the workflow on pull request
  pull_request

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  pr:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      # Setup
      - name: ⚙️ Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: ⚙️ Configure AWS credentials (For package registry pulling)
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ secrets.AWS_CODEARTIFACT_ROLE_ARN }}
          aws-region: eu-west-2

      - name: ⚙️ Configure Codeartifact
        run: aws codeartifact login --tool npm --repository registry-prod-repo --domain registry-prod --domain-owner ${{ secrets.AWS_CODEARTIFACT_ACCOUNT_ID }} --region eu-west-2

      - name: ⚙️ Setup pnpm
        uses: pnpm/action-setup@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: ⚙️ Install Dependencies
        run: pnpm install

      - name: ⚙️ Validate Typescript
        run: pnpm build:validate

      - name: 🔨 Build bundles
        run: pnpm build

      # Formatting
      - name: 📝 Run Lint
        run: pnpm lint

      # Testing
      - name: 🧪 Run Unit tests & report coverage
        id: unittests
        run: |
          echo "Test results:" > coverage.md
          echo '```' >> coverage.md
          (pnpm run test:coverage 2>&1 | grep -A1000 "= Coverage summary =" | tee -a coverage.md) || echo "Failed to meet the criteria"
          echo '```' >> coverage.md
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"

          echo 'report<<EOF' >> $GITHUB_OUTPUT
          cat coverage.md >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: 🧪 Create Comment with Test results
        uses: hasura/comment-progress@146c635f3e325d478025e29e5043ec1c07c0e36c # v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'govuk-once/gds-unified-notification-service'
          number: ${{ github.event.number }}
          id: unittestscomment
          message: '${{steps.unittests.outputs.report}}'
          recreate: true

      # CDK Validation - Explicitly ovewriting AWS env vars so CDK:SYNTH ignores assumed role
      - name: 🏗️ CDK Synth
        if: success() || failure() # Until TF Migration is completed
        run: |
          env=cicd AWS_REGION=eu-west-2 AWS_DEFAULT_REGION=eu-west-2 AWS_ACCESS_KEY_ID="" AWS_SECRET_ACCESS_KEY="" AWS_SESSION_TOKEN="" pnpm cdk:synth

      - name: 🔐 Checkov GitHub Action
        if: success() || failure()
        uses: bridgecrewio/checkov-action@8f61ce5b8a3afb4ca94d236b75201878ded6d2cd # v12
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif
          soft_fail: true
          framework: cloudformation
          directory: infrastructure/cdk/cdk.out/
          config_file: .checkov.yaml
          quiet: true

      - name: ⚙️ Upload SARIF file
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        if: success() || failure()
        with:
          sarif_file: results.sarif

      # SonarQube - Scan, Gate, Report
      - name: 🕵🏻 Run SonarQube Scan
        continue-on-error: true
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_UNS }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}

      - name: 🕵🏻 SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        continue-on-error: true
        uses: sonarsource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b # v1.2.0
        if: success() || failure()
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_UNS }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}

      - name: 🕵🏻 Create Comment with SonarQube's Quality Gate
        continue-on-error: true
        uses: hasura/comment-progress@146c635f3e325d478025e29e5043ec1c07c0e36c # v2.3.0
        if: success() || failure()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'govuk-once/gds-unified-notification-service'
          number: ${{ github.event.number }}
          id: qualitygatecomment
          message: 'SonarQube Quality Gate Status: ${{steps.sonarqube-quality-gate-check.outputs.quality-gate-status}} [LINK](https://sonarcloud.io/summary/new_code?id=govuk-once_gds-unified-notification-service&pullRequest=${{github.event.number}})'
          recreate: true
